# -*- coding: utf-8 -*-
"""read_data_preprocessing alzheimer kaggle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I_2QDOnky98-Qgnn8GRNt5fY7BwvKd3B
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df  = pd.read_csv("/content/drive/MyDrive/data_kaggle/alzheimers_disease_data.csv")
df.head()

df.info()
df.describe()
df.isnull().sum()

df.shape

df.columns

df.isnull()

df.isnull().sum()

df["Diagnosis"].value_counts()

x=df.drop("Diagnosis", axis=1)
y=df['Diagnosis']

df.columns

x=df.drop("PatientID", axis=1)

# x=df.drop("DoctorInCharge", axis=1)

x = np.array(x)
y = np.array(y)

x.shape , y.shape

df.info()

df['DoctorInCharge']=df['DoctorInCharge'].astype('category')

df.info()

df["DoctorInCharge"].value_counts()

df["DoctorInCharge"]=df["DoctorInCharge"].cat.codes

df["DoctorInCharge"].value_counts()



from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y)
y = le.transform(y)
y



df["DoctorInCharge"]

x = df.select_dtypes(include=['number'])

print(x.dtypes)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)

x

import os
import numpy as np


folder_path = "/content/drive/MyDrive/data_kaggle/alzheimers_disease_data"
os.makedirs(folder_path, exist_ok=True)



np.save("/content/drive/MyDrive/data_kaggle/alzheimers_disease_data/X.npy", x)
np.save("/content/drive/MyDrive/data_kaggle/alzheimers_disease_data/y.npy", y)